### ISSUE TITLE
Application stops working after a while

### ISSUE THREAD

**Issue by Tanuj27** [BridgeSenseDev/Dank-Memer-Grinder#165]
**Describe the bug**
App stops working after a few uses and this comes up

**Error**
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 95, in create_connection
  File "urllib3\util\connection.py", line 85, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 363, in connect
  File "urllib3\connection.py", line 179, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002571D54C4D0>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /BridgeSenseDev/Dank-Memer-Grinder/main/resources/version.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002571D54C4D0>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 669, in <module>
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 553, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /BridgeSenseDev/Dank-Memer-Grinder/main/resources/version.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002571D54C4D0>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)'))

**Screenshots**
![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/70958473/80b736e6-79f3-43e0-a4f5-f5079da31079)

**OS:**
Windows 11

**Comment by BridgeSenseDev** [comment]
Your isp blocks https://raw.githubusercontent.com, will be fixed next release
