### ISSUE TITLE
Traceback (most recent call last):   File "main.py", line 740, in <module> ValueError: invalid literal for int() with base 10: '404: Not Found'

### ISSUE THREAD

**Issue by DalotuberTSL** [BridgeSenseDev/Dank-Memer-Grinder#239]
**Describe the bug**
I open the EXE and it says the error

**Error**
Traceback (most recent call last):
  File "main.py", line 740, in <module>
ValueError: invalid literal for int() with base 10: '404: Not Found'

**Screenshots**

**OS:**
Windows

**Comment by arlohewitt** [comment]
same

**Comment by MysteryDealer** [comment]
![image](https://github.com/user-attachments/assets/982eb849-fe8d-481d-a8df-b7fb9cb313be)
same here

**Comment by BridgeSenseDev** [comment]
https://docs.dankmemer.tools/installation/pre-built-binaries
