### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by drachedachte1** [BridgeSenseDev/Dank-Memer-Grinder#40]
![image](https://user-images.githubusercontent.com/65346683/210829215-f8c51cb2-7627-47d8-9cb8-3b761efd7d34.png)
`‎Ignoring exception in on_message‎
‎Traceback (most recent call last):
‎‎  File "discord\client.py", line 396, in _run_event
‎‎  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI52682\cogs\stream.py", line 79, in on_message
    await self.bot.select(message, 0, 0, game)
                                         ^^^^
‎‎NameError: name 'game' is not defined`

seems like overall its working

**Comment by drachedachte1** [comment]
im using a amazon windows server to have it run 24/7

**Comment by BridgeSenseDev** [comment]
Invite shero bot to your discord from https://discord.com/oauth2/authorize?client_id=692570006969516032&permissions=141130460407&scope=applications.commands%20bot. The bot gets the trending game using this bot but next release ill make it so you dont need this bot anymore

**Comment by drachedachte1** [comment]
> Invite shero bot to your discord from [discord.com/oauth2/authorize?client_id=692570006969516032&permissions=141130460407&scope=applications.commands%20bot](https://discord.com/oauth2/authorize?client_id=692570006969516032&permissions=141130460407&scope=applications.commands%20bot). The bot gets the trending game using this bot but next release ill make it so you dont need this bot anymore

uhm what 
what does that bot have to do with a dank memer grinder self bot?

**Comment by BridgeSenseDev** [comment]
> > Invite shero bot to your discord from [discord.com/oauth2/authorize?client_id=692570006969516032&permissions=141130460407&scope=applications.commands%20bot](https://discord.com/oauth2/authorize?client_id=692570006969516032&permissions=141130460407&scope=applications.commands%20bot). The bot gets the trending game using this bot but next release ill make it so you dont need this bot anymore
> 
> uhm what what does that bot have to do with a dank memer grinder self bot?

It uses shero bot to get the trending game for streaming so you need to invite it, ill change that later

**Comment by BridgeSenseDev** [comment]
Fixed already
