### ISSUE TITLE
Long term use error

### ISSUE THREAD

**Issue by red78massive1573** [BridgeSenseDev/Dank-Memer-Grinder#91]
**Describe the bug**
After letting the program run a long time, it will slowly stop sending commands

**Error**
```
‎‎Unhandled exception in internal background task 'commands'.‎
‎Traceback (most recent call last):
‎‎  File "discord\ext\tasks\__init__.py", line 241, in _loop
‎‎  File "C:\Users\owenh\AppData\Local\Temp\_MEI19522\cogs\commands.py", line 45, in commands
    await self.bot.send(self.bot.commands_dict[command])
‎‎  File "main.py", line 222, in send
‎‎  File "discord\commands.py", line 621, in __call__
‎‎TypeError: Cannot use a group
```

**OS:**
Windows

**Comment by red78massive1573** [comment]
it is version 1.5.2

**Comment by red78massive1573** [comment]
For people that wants a way out off this: #98
